// Quick test of the markdown parser

function parseSkillMarkdownOutput(markdown) {
  const concepts = [];

  // Split by ## TWEET markers
  const tweetSections = markdown.split(/##\s*TWEET\s*#(\d+):/);

  // Process each tweet section (skip first element which is intro text)
  for (let i = 1; i < tweetSections.length; i += 2) {
    const number = parseInt(tweetSections[i]);
    const content = tweetSections[i + 1];

    if (!content) continue;

    // Extract title from first line
    const lines = content.trim().split('\n');
    const title = lines[0].trim();

    // Extract all posts (content between ``` markers)
    const posts = [];
    const codeBlockRegex = /```\s*\n([\s\S]*?)\n```/g;
    let match;

    while ((match = codeBlockRegex.exec(content)) !== null) {
      posts.push(match[1].trim());
    }

    // Last post is the CTA
    const cta = posts.length > 0 ? posts.pop() : '';
    const mainPosts = posts;

    if (mainPosts.length > 0) {
      concepts.push({
        number,
        title,
        concept: title,
        strategy: 'What-Why-Where cycle with contextual CTA',
        mainContent: {
          posts: mainPosts,
          characterCounts: mainPosts.map(p => `${p.length}/500 ${p.length <= 500 ? '✅' : '❌'}`)
        },
        cta: cta,
        ahamoment: mainPosts[0],
        qualityValidation: `Generated by content-to-tweets skill with ${mainPosts.length} posts`
      });
    }
  }

  return concepts;
}

const sampleMarkdown = `
## TWEET #1: The Value of Free Time as a Business Owner

Post 1:
\`\`\`
Working 2 Hours a day and having the rest of the day to do what you want isn't just a lifestyle choice - it's a strategic advantage.

Free time is leverage. And in today's rapidly evolving AI landscape, it's becoming the ultimate competitive edge.
\`\`\`

Post 2:
\`\`\`
Why? Because while most business owners are stuck in operations, those with free time can:

• Innovate their products
• Build their brand quickly
• Capitalize on emerging AI opportunities
• Stay ahead of market shifts

The 2-hour business owner isn't lazy - they're strategic.
\`\`\`

CTA Tweet:
\`\`\`
Understanding the value of free time is one thing.

Knowing how to leverage it specifically for AI innovation is different.

I share insights about operational efficiency and AI leverage in my daily email.

Join to get perspectives that build businesses running without you:

your_newsletter_link
\`\`\`

## TWEET #2: Another Concept

Post 1:
\`\`\`
This is another tweet concept.
\`\`\`

CTA Tweet:
\`\`\`
The CTA for tweet 2.
\`\`\`
`;

console.log('🧪 Testing markdown parser...\n');

const result = parseSkillMarkdownOutput(sampleMarkdown);

console.log(`✅ Parsed ${result.length} concepts\n`);

result.forEach((concept, i) => {
  console.log(`📝 Concept ${i + 1}:`);
  console.log(`   Number: ${concept.number}`);
  console.log(`   Title: ${concept.title}`);
  console.log(`   Main Posts: ${concept.mainContent.posts.length}`);
  console.log(`   CTA Length: ${concept.cta.length} characters`);
  console.log(`   Character Counts: ${concept.mainContent.characterCounts.join(', ')}`);
  console.log('');
});

console.log('📤 Full Structure of First Concept:');
console.log(JSON.stringify(result[0], null, 2));
